### ISSUE TITLE
Windows Cryptofolio V1.1: Uncaught exception, cannot read port property of null

### ISSUE THREAD

**Issue by calgara12** [Xtrendence/Cryptofolio#12]
Hey, i just downloaded the new  Windows release, and when i execute the .exe i immediately get prompted with an uncaught exception saying cannot read port property of null:
![image](https://user-images.githubusercontent.com/28657023/113142711-80f94180-922b-11eb-8cc0-195fdae7bf80.png)

Thanks for all your work and have a nice day!

**Comment by Xtrendence** [comment]
Hey! :) 

Hmmm, interesting, I’ve replaced the release files now, so give this one a try (https://github.com/Xtrendence/Cryptofolio/releases/download/V.1.1/Cryptofolio-Windows-1.0.0.exe <https://github.com/Xtrendence/Cryptofolio/releases/download/V.1.1/Cryptofolio-Windows-1.0.0.exe>). Hopefully it works now.

**Comment by Xtrendence** [comment]
Aaaaaaand I’ve replaced it again, sorry, I think I fixed it this time though.

**Comment by Xtrendence** [comment]
I can confirm it's working on my PC. You might have to uninstall it first before reinstalling to make sure it's a fresh copy.

**Comment by calgara12** [comment]
Yeah thanks, now it works
