### ISSUE TITLE
Support for different currencies

### ISSUE THREAD

**Issue by calgara12** [Xtrendence/Cryptofolio#13]
Hey, is it possible to see the coin value in a different currency than the USD, like for example in EUR?

**Comment by Xtrendence** [comment]
Currently that's not an option, but I'll add it to the list of features to add later on. I'll be adding the ability to record transactions first, then I'll add that as well. On Mar 31, 2021 2:26 PM, calgara12 ***@***.***> wrote:
Hey, is it possible to see the coin value in a different currency than the USD, like for example in EUR?

**Comment by Xtrendence** [comment]
I'll be drafting a new release in a bit after I test everything, but support for GBP and EUR has been added to all platforms. Figured it was way easier to add that than transactions so might as well.
