### ISSUE TITLE
Feature Request: CSV transaction import

### ISSUE THREAD

**Issue by calgara12** [Xtrendence/Cryptofolio#14]
Hey, first of all, thanks for all the work you do, i really appreciate it.

I have an idea which could be really useful, for people to migrate to your app: The possibility to import transactions via a csv file, or something along those lines. I already know that you are working on a feature to add manual transactions, but it would be a lot easier to just import them.

Thanks and have a nice day!

**Comment by Xtrendence** [comment]
Hi, and thank you for the suggestion. Initially, I was going to add an import feature for Delta specifically as another user on Reddit wanted to import their transactions, but I'm thinking of a way to allow imports from anywhere as long as it's a CSV file and has the required headers. This does mean however that the user importing the file would likely have to modify it to include the fields necessary, as it'd be nearly impossible for me to accommodate all the different possible variations. 

This is subject to change, so I wouldn't base the CSV off of this until I finish adding the feature, but currently this is what would be expected:

**If it's a transaction (buy/sell):**

Relevant Headers: id, symbol, date, type, amount, fee, notes, exchange, pair, price

Example Row: bitcoin, btc, 2021-04-06T07:15:16Z, sell, 0.01, 3, To pay the rent, Binance, btc/usd, 58000

**If it's a transfer:**

Relevant Headers: id, symbol, date, type, amount, fee, notes, from, to

Example Row: bitcoin, btc, 2021-04-06T07:15:16Z, transfer, 0.25, 5, Moving to cold wallet, Wallet, Wallet

The ID would be the CoinGecko coin ID, the date can be any format really as long as PHP's "strtotime" function can parse it, the type has to be "buy", "sell", or "transfer",  "notes" can be left empty. 

Overall then, your CSV headers would be the following:

id, symbol, date, type, amount, fee, notes, exchange, pair, price, from, to

Where you'd leave "exchange", "pair", and "price" empty if the "type" is "transfer", and the "from" and "to" empty if the "type" is "buy" or "sell". So those two rows above in an actual file you'd import would look something like this:

bitcoin, btc, 2021-04-06T07:15:16Z, sell, 0.01, 3, To pay the rent, Binance, btc/usd, 58000,,
bitcoin, btc, 2021-04-06T07:15:16Z, transfer, 0.25, 5, Moving to cold wallet,,,, Wallet, Wallet

**Comment by Xtrendence** [comment]
Again, I'd avoid modifying any CSV files to match that format right now, as I'm also looking into scraping CoinGecko so I can provide a way to just use an asset's ticker/symbol and forego the ID entirely.

**Comment by calgara12** [comment]
yeah, that would be great. This project really looks promising.

Thanks!

**Comment by Xtrendence** [comment]
I'm closing this issue, but you can keep up with the progress of this feature by looking at the [project board](https://github.com/Xtrendence/Cryptofolio/projects/1). I expect this to be added in version 1.4 though rather than the upcoming 1.3 update as it entails quite a bit of work. Currently, I'm going to try to add the activity/transactions page before the end of April as I have university coursework and a bunch of deadlines for May. Once I add that, I'll add an import/export feature.
