### ISSUE TITLE
Feature Request - Record - Choose from a Pop Up Calender 

### ISSUE THREAD

**Issue by Cebrain** [Xtrendence/Cryptofolio#48]
I found today your project on reddit and it looks great to replace a online tracking tool.

For setting a record it would be great if it would be possible with a PopUp Calender because to write down the date and time needs much time.

Example taken from Rokti [https://github.com/rotki/rotki](url)

![image](https://user-images.githubusercontent.com/78339531/123769791-f11a7080-d8c9-11eb-8882-ceac48bf8162.png)

**Comment by Xtrendence** [comment]
That's a good point, I must've missed that because I generally recorded transactions using a desktop, so it was easier to just write like 2021/06/29 than to use a popup. I might add a little calendar button to the side of the input field so you have the option to do whichever way you prefer.

**Comment by Xtrendence** [comment]
Added to the [project board](https://github.com/Xtrendence/Cryptofolio/projects/1#card-64324832).
