### ISSUE TITLE
Multi-Arch Docker Builds

### ISSUE THREAD

**Issue by Xtrendence** [Xtrendence/Cryptofolio#50]

**Comment by Hukuma1** [comment]
My RPi will thank you for this. :D

**Comment by Xtrendence** [comment]
Hi, could you just check to see if `docker pull xtrendence/cryptofolio:V.2.1.0-arm64` works on your Pi? I'm not entirely sure how to bundle all the builds together, but for now, I just want to see if that works, and then for the next release I'll figure out how to group them all together.

**Comment by viandika** [comment]
Yep. I can confirm it running on my Pi4 raspbian 64bit.

**Comment by Xtrendence** [comment]
Thank you. Could you please also try out `docker pull xtrendence/cryptofolio:latest`? I've bundled them together, but can't test ARM64. Thanks again!

**Comment by viandika** [comment]
The ARM64 build from the bundle runs great for me too. :D

**Comment by Xtrendence** [comment]
Okay, I'll delete the separate ones then and leave the bundle, and replace V.2.1.0 with a bundle of its own.
