### ISSUE TITLE
[FR] Dashboard improvements

### ISSUE THREAD

**Issue by Hukuma1** [Xtrendence/Cryptofolio#52]
Currently the `Dashboard` shows you the Top 10 coins by Marketcap (I think?) and to the right a section of your coin holdings.

To make it a bit more custom, could we please:

1. Add the ability to track specific coins (which we don't hold, but just want to keep an eye on maybe)

2. Add the 24 hour change to the coins we hold

3. Colorize the gains and losses of the numbers. e.g. red -3% and green 3% (I know in settings there's a way to colorize the whole table cell, but would like to see it just for the number)

4. Add market cap position to coins held on `Dashboard` or in `Holdings`. Otherwise unless you're only holding top 10 coins you won't really know how well or poor your other ones are ranked.

5. Add the ability to sort the lists via all the different metrics. e.g. clicking on `Amount` will sort it greatest -> smallest amount for all coins.

**Comment by Xtrendence** [comment]
Thank you so much for these suggestions, I absolutely love all of them. I don't know why I was so dismissive of the dashboard during development,  but I can definitely see now how useful it could be. I'll be sure to include most or all of this in the next release if I can! Thank you again, people like you keep the project alive and help it improve.

**Comment by Xtrendence** [comment]
Oh and thanks for the specific and detailed examples and descriptions too.

**Comment by Xtrendence** [comment]
Added to the [project board](https://github.com/Xtrendence/Cryptofolio/projects/1#card-64324788).
