### ISSUE TITLE
API responses 200 but not doing anything

### ISSUE THREAD

**Issue by JBrame** [Xtrendence/Cryptofolio#72]
This is an issue with my requests I'm sure - do you have some sample requests you can share?

This is what I'm trying and variations of JSON, and parameterised URL etc, but no matter what I try it returns 200 but hasn't actually done anything

POST /api/accounts/login.php HTTP/1.1
Host: {URL}
Content-Type: application/json
Content-Length: 79

{
    "username": "admin",
    "password": "admin",
    "platform": "web"
}

**Comment by Xtrendence** [comment]
That's my bad actually, the documentation should've made it clear. The "platform" should be passed in the URL as a GET request query string like so:

`http://localhost/api/accounts/login.php?platform=web`

**Comment by JBrame** [comment]
Thank you for such a quick reply! Got it working now!
