### ISSUE TITLE
API : I can get token from login.php but any GET returns 200 Ok without data

### ISSUE THREAD

**Issue by tibuski** [Xtrendence/Cryptofolio#76]
I am running last version  via docker.

```python
import requests

r = requests.post('http://nuc.lan:8080/api/accounts/login.php?platform=web', data={"platform":"web", "username":"admin", "password":"admin"})

reply = r.json()

print(reply['token'])

holdings = requests.get('http://nuc.lan:8080/api/holdings/read.php?platform=web', data={"token":reply['token'], "username":"admin"})

print(holdings.content)
```

**Note :** I am a beginner in Python, please forgive any obvious mistake :)

**Comment by Xtrendence** [comment]
Hi, I believe with GET requests, I have the API set up to fetch data from the URL, so you'd have to pass them as query strings like so:

read.php?platform=web&token=token&username=username

Where you'd of course get the token and username from the login response. :)

**Comment by tibuski** [comment]
Ohh, from the doc I thought it was only for platform=web :)

It works ! Thank you !
